### ISSUE TITLE
TASK#03.4 - Wrapping-up: Generació de l'entorn final per a la realització de la PoC

### ISSUE THREAD

**Issue by jbericat** [UOC-Assignments/uoc.tfg.jbericat#73]
Ja es disposa de tots els elements necessaris per a generar el mapa o entorn final per a realitzar la PoC. Com que la decisió final ha sigut la de utilitzar imatges que simulen visió termal nocturna de tipus FLIR, i la simulació d'aquesta que s'ha implementat (veure #65) té la limitació de no poder assignar un blueprint de calor als efectes VFX de foc de tipus `emitter`, aleshores s'haurà d'afegir un objecte "base" a cada flama o zona amb foc de tipus `StaticMeshActor`.

ATENCIÓ: Per a generar l'entorn s'ha de seguir exactament la següent seqüència, ja que treballar amb l'editor UE4 + la CPU de què disposo (del 2010) no em permet anar obrint i tancant, guardant, etc el projecte amb agilitat, i aquest té tendencia a crashes de manera freqüent. Així doncs s'ha d'anar per fases per tal de no haver de fer la feina diverses vegades:

- [x] 1. Selecció de 4 àrees d'incendi clarament delimitades que simulin diferents intensitats i/o condicions (alçada flames, fum, extensió, visibilitat, accesibilitat, etc) -> **Accions:** Generar una captura de pantalla  "vista aguila" i etiquetar+delimitar cada zona 
- [x] 2. Colocar els objectes tipus `staticMeshActor` a cadascuna de les àrees delimitades al punt anterior
- [x] 3. Guardar i reobrir el projecte (num. versió +1)
- [x] 4. Afegir els VFX de foc de tipus `emitter` SUPERPOSATS sobre cadascun dels objectes de tipus `StaticMeshActor` afegits al punt 2 -> #45 
- [x] 5. Guardar i reobrir el projecte (num. versió +1)
- [x] 6. Establir diferents posicionaments de la càmera per a prendre les imatges (això és alçada i angle, ja que la càmera es mou automàticament a les coordenades on hi ha els `StaticMeshActors` que simulen emissió de calor). **Accions:** Definir posicionaments, desar en una estructura de dades i "injectar-les" al codi python `capture_ir_segmentation.py` com a input data -> #75
- [x] 7. Testejar tot el setup AMB iluminació 
- [x] 8. Desactivar la iluminació de l'entorn -> #44 
- [x] 9. Testejar tot el setup SENSE iluminació
- [x] 10. Guardar i reobrir el projecte (num. versió +1)
- [ ] 11. Generar els binaris de l'entorn final UE4 de la PoC
